algorithm: deep_q_learning
seed: 1024
solver:
    env: PongNoFrameskip-v4
    lr: 0.0001
    gamma: 0.99
    episodes: 1000
    frame_stack: 4
    target:
        update_mode: framed  # episodic, framed
        update_freq: 1000
    loss: smooth_l1_loss
    optimizer: Adam
greedy:
    mode: framed  # episodic, framed
    start: 1
    steps: 200000
    end: 0.02   
replay:
    capacity: 10000
    sample_batch: 32
record:
    save_freq: 20
    save_path: ./checkpoint
    render: False
    debug: False
    
