algorithm: deep_q_learning
seed: 123
solver:
    env: PongNoFrameskip-v4
    lr: 0.0001
    gamma: 0.99
    episodes: 1000
    frame_stack: 4
    target:
        update_mode: framed  # episodic, framed
        update_freq: 4000
    loss: smooth_l1_loss
    optimizer: Adam
greedy:
    mode: framed  # episodic, framed
    start: 1
    end: 0.02
    steps: 409600
    decay: linear  # linear, exponential
replay:
    capacity: 100000
    sample_batch: 128
record:
    save_freq: 20
    save_path: ./checkpoint
    render: False
    debug: False
    
