algorithm: deep_q_learning
seed: 123
solver:
    env: PongNoFrameskip-v4
    lr: 0.0001
    gamma: 0.99
    episodes: 4000
    frame_stack: 4
    learn_freq: 1
    target:
        update_mode: framed  # episodic, framed
        update_freq: 1000
    loss: smooth_l1_loss
    optimizer: RMSprop 
greedy:
    mode: framed  # episodic, framed
    start: 1
    end: 0.02
    steps: 102400
    delay: 40000
    decay: linear  # linear, exponential
replay:
    capacity: 100000
    init_num: 10000
    sample_batch: 32
record:
    save_freq: 20
    save_path: ./checkpoint
    render: False
    debug: False
    
